In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print('arr - ')
print(arr)

print('-------------')

print('shape - ')
print(arr.shape)

print('-------------')

print('size - ')
print(arr.size)

print('-------------')

print('dimension - ')
print(arr.ndim)

arr - 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------
shape - 
(3, 4)
-------------
size - 
12
-------------
dimension - 
2


In [3]:
print('First row of an array')
arr[1]

First row of an array


array([5, 6, 7, 8])

In [4]:
arr[2][3]

12

In [5]:
l = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
def ExtractOdd(arr):
    for i in range(len(arr)):
        for j in range(len(arr)+1):
            if j %2!=0:
                print(arr[i][j], end=',')



In [7]:
ExtractOdd(arr)

2,4,6,8,10,12,

In [8]:
arr[0:3,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [9]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

np.random.randint(0,2, (3,3))

array([[0, 1, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [11]:
np.expand_dims(arr, axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [12]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [13]:
matrixA2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matrixB2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [14]:
matrixA2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
matrixB2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
#1. Index wise multiplication


matrixA2 * matrixB2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [17]:
# Matrix multiplication

matrixB3 = matrixB2.reshape(4,3)
matrixA2 @ matrixB3

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [18]:
# Add both the maticx

matrixA2 + matrixB2


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [19]:
#Subtact matix B from matrix A

matrixB2 - matrixA2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
#Divide matrix B by A

matrixB2 / matrixA2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#12. Which function in Numpy can be used to swap the byte order of an array?

print('Before - ')
print(arr)

print()
print('After byt swap - ')
arr2 = arr.byteswap()
arr2

Before - 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

After byt swap - 


array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])